server {
    # コンテナ内の80番ポートでHTTPリクエストを受け付ける
    listen 80;
    server_name localhost;
    # PHPファイルを探すルートディレクトリ
    root /var/www/html/public;
    # アクセス時のデフォルトで読むファイル
    index index.php index.html;

    # 全リクエストに対して、実ファイル→ディレクトリの順で探す（左の定義から順に探す）
    # $uri: リクエストされたパスをそんままファイルとして探す
    # $uri/: リクエストされたパスをディレクトリとして探す
    # /index.php?$query_string: クエリとして探す
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # .phpで終わるURLを正規表現でマッチ
    location ~ \.php$ {
        # 9000番ポートでリクエストを転送
        fastcgi_pass app:9000;
        # ディレクトリ指定時のデフォルトPHPファイル
        fastcgi_index index.php;
        # どのPHPを実行するのか、絶対パスを伝える
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # fastcgi通信に必要な標準パラメータ群を読み込む
        include fastcgi_params;
    }
}